### ISSUE TITLE
Icons Appear Broken

### ISSUE THREAD

**Issue by cybardev** [strafe/bunnyfetch#1]
I'm using iTerm2 with Caskaydia Nerd Font.
Tried JetBrains and Meslo Nerd Fonts too.

Any idea how to fix this?
What font did you use for the screenshot?

![image](https://user-images.githubusercontent.com/50134239/150185468-03002828-f812-48d4-b463-02e4e9e99e34.png)

**Comment by strafe** [comment]
Hey - that's strange. Can you try running the command below and check that the majority of the symbols are working for you? (the font used is Caskaydia Nerd Font).
```bash
bash <(curl -s https://raw.githubusercontent.com/ryanoasis/nerd-fonts/master/bin/scripts/test-fonts.sh)
```

**Comment by cybardev** [comment]
Here's the output from that command:

<details><summary>Output (click to expand)</summary><br>
Nerd Fonts - Pomicons

/dev/fd/11: line 102: mapfile: command not found
╔══════╦══════╦══════╦══════╦══════╗
╚══════╩══════╩══════╩══════╩══════╝


Nerd Fonts - Powerline

/dev/fd/11: line 102: mapfile: command not found
/dev/fd/11: line 102: mapfile: command not found
╔══════╦══════╦══════╦══════╦══════╗
╚══════╩══════╩══════╩══════╩══════╝


Nerd Fonts - Powerline Extra

/dev/fd/11: line 102: mapfile: command not found
/dev/fd/11: line 102: mapfile: command not found
/dev/fd/11: line 102: mapfile: command not found
/dev/fd/11: line 102: mapfile: command not found
╔══════╦══════╦══════╦══════╦══════╗
╚══════╩══════╩══════╩══════╩══════╝


Nerd Fonts - Symbols original

/dev/fd/11: line 102: mapfile: command not found
╔══════╦══════╦══════╦══════╦══════╗
╚══════╩══════╩══════╩══════╩══════╝


Nerd Fonts - Devicons

/dev/fd/11: line 102: mapfile: command not found
╔══════╦══════╦══════╦══════╦══════╗
╚══════╩══════╩══════╩══════╩══════╝


Nerd Fonts - Font awesome

/dev/fd/11: line 102: mapfile: command not found
╔══════╦══════╦══════╦══════╦══════╗
╚══════╩══════╩══════╩══════╩══════╝


Nerd Fonts - Font awesome extension

/dev/fd/11: line 102: mapfile: command not found
╔══════╦══════╦══════╦══════╦══════╗
╚══════╩══════╩══════╩══════╩══════╝


Nerd Fonts - Octicons

/dev/fd/11: line 102: mapfile: command not found
/dev/fd/11: line 102: mapfile: command not found
/dev/fd/11: line 102: mapfile: command not found
/dev/fd/11: line 102: mapfile: command not found
╔══════╦══════╦══════╦══════╦══════╗
╚══════╩══════╩══════╩══════╩══════╝


Nerd Fonts - Font Linux

/dev/fd/11: line 102: mapfile: command not found
╔══════╦══════╦══════╦══════╦══════╗
╚══════╩══════╩══════╩══════╩══════╝


Nerd Fonts - Font Power Symbols

/dev/fd/11: line 102: mapfile: command not found
/dev/fd/11: line 102: mapfile: command not found
╔══════╦══════╦══════╦══════╦══════╗
╚══════╩══════╩══════╩══════╩══════╝


Nerd Fonts - Material Design Icons

/dev/fd/11: line 102: mapfile: command not found
╔══════╦══════╦══════╦══════╦══════╗
╚══════╩══════╩══════╩══════╩══════╝


Nerd Fonts - Weather Icons

/dev/fd/11: line 102: mapfile: command not found
╔══════╦══════╦══════╦══════╦══════╗
╚══════╩══════╩══════╩══════╩══════╝


Nerd Fonts - All

/dev/fd/11: line 102: mapfile: command not found
/dev/fd/11: line 102: mapfile: command not found
/dev/fd/11: line 102: mapfile: command not found
/dev/fd/11: line 102: mapfile: command not found
/dev/fd/11: line 102: mapfile: command not found
/dev/fd/11: line 102: mapfile: command not found
/dev/fd/11: line 102: mapfile: command not found
/dev/fd/11: line 102: mapfile: command not found
/dev/fd/11: line 102: mapfile: command not found
/dev/fd/11: line 102: mapfile: command not found
/dev/fd/11: line 102: mapfile: command not found
/dev/fd/11: line 102: mapfile: command not found
/dev/fd/11: line 102: mapfile: command not found
/dev/fd/11: line 102: mapfile: command not found
/dev/fd/11: line 102: mapfile: command not found
/dev/fd/11: line 102: mapfile: command not found
/dev/fd/11: line 102: mapfile: command not found
/dev/fd/11: line 102: mapfile: command not found
/dev/fd/11: line 102: mapfile: command not found
/dev/fd/11: line 102: mapfile: command not found
╔══════╦══════╦══════╦══════╦══════╗
╚══════╩══════╩══════╩══════╩══════╝

</details>

Also, I forgot to mention. I have Typicons installed too.

**Comment by strafe** [comment]
Right... apparently `mapfile` isn't supported in Bash 3 which is kind of annoying. You can run the last version of the script that supports it (hopefully) and see what that spits out:
```bash
bash <(curl -s https://raw.githubusercontent.com/ryanoasis/nerd-fonts/2f13a0d2691abe30935ff9a1b288ce76bb9f7824/bin/scripts/test-fonts.sh)
```

**Comment by cybardev** [comment]
That command produced a lot of output...

I couldn't comment it here, so I made a `gist` of it:
[https://gist.github.com/cybardev/font_log.txt](https://gist.githubusercontent.com/cybardev/8e57725eeb6a2fa4b9b4680f3fec352d/raw/5299c8ce9a405654f5003a7b67c5dda4e861abad/font_log.txt)

**Comment by strafe** [comment]
A screenshot would be ideal, it should print out a bunch of the nerd font icons e.g.
<img width="300" alt="CleanShot 2022-01-23 at 22 02 19@2x" src="https://user-images.githubusercontent.com/15663890/150699595-3b8eec10-f98a-4cb5-8cb2-717518ae1b33.png">

**Comment by cybardev** [comment]
It's a lot of output. Here are the first 3 screens:

![image](https://user-images.githubusercontent.com/50134239/150703449-ad7e5356-a893-4069-8093-c842e3f021f0.png)

**Comment by cybardev** [comment]
Okay, I think I see the issue here. `Kitty` renders the icons properly:

![image](https://user-images.githubusercontent.com/50134239/150703703-3e81d770-9692-4fbe-84df-4336606a596b.png)

The issue may be with `iTerm2` not being able to recognize and/or render Typicons.

**Comment by strafe** [comment]
I haven't used any typicons in this, all of the symbols are nerd fonts icons. Personally I'm using iTerm2 and have no issues. Where did you install the font?

<img width="944" alt="CleanShot 2022-01-24 at 00 09 20@2x" src="https://user-images.githubusercontent.com/15663890/150703877-f8925916-bb9c-43a2-869a-b74c4abb161f.png">

**Comment by cybardev** [comment]
This is very odd... I toggled ligatures off and then on again, and now all the icons render fine. Didn't need to change the font or anything. Maybe it just didn't "update" till now or something.

Thank you for your kind help. Much appreciated. 😊

**Comment by strafe** [comment]
No worries! You may also want to disable mark indicators (the little blue arrows), I see them in your first screenshot. They annoyed me for a while.
<img width="396" alt="CleanShot 2022-01-24 at 00 26 45@2x" src="https://user-images.githubusercontent.com/15663890/150704577-ab90735d-893e-4e28-916e-fd9cd583e6a1.png">

**Comment by cybardev** [comment]
Oh yeah, that's very annoying. Looks much cleaner now. Thanks a lot.

---

unrelated, but could you suggest how I can put the parts to print system information in their own function?

So this...
```sh
printf '\n             %s%s%b  %s%s\n   (\ /)     %s%b  %s%s\n   ( %s. .%s)    %s%b  %s%s\n   c(%s"%s)(%s"%s)   %s%b  %s%s\n             %s%b  %s%s\n\n' \
    "$d" "$c1" '\xEF\x82\x8A' "$t" "$window_manager" \
    "$c3" '\xEF\x82\xAD' "$t" "$kernel_version" \
    "$d" "$t" "$c2" '\xEF\x84\xA0' "$t" "$current_shell" \
    "$c1" "$t" "$c1" "$t" "$c5" '\xEF\x80\xBE' "$t" "$resolution" \
    "$c4" '\xEF\x87\xAB' "$t" "$wifi_ssid"
```

Would be like:
```sh
sysinfo() {
    "$d" "$c1" '\xEF\x82\x8A' "$t" "$window_manager" \
    "$c3" '\xEF\x82\xAD' "$t" "$kernel_version" \
    "$d" "$t" "$c2" '\xEF\x84\xA0' "$t" "$current_shell" \
    "$c1" "$t" "$c1" "$t" "$c5" '\xEF\x80\xBE' "$t" "$resolution" \
    "$c4" '\xEF\x87\xAB' "$t" "$wifi_ssid"
}

printf '\n             %s%s%b  %s%s\n   (\ /)     %s%b  %s%s\n   ( %s. .%s)    %s%b  %s%s\n   c(%s"%s)(%s"%s)   %s%b  %s%s\n             %s%b  %s%s\n\n' \
    $(sysinfo)
```

Or such...

It's actually an XY problem. My real intention is to avoid code duplication in my fork of this script:
```sh
kittyfetch() {
    printf '\n             %s%s%b  %s%s\n   /\_/\     %s%b  %s%s\n  ( %s%s%s )    %s%b  %s%s\n   %s>%s %s^%s %s<%s     %s%b  %s%s\n             %s%b  %s%s\n\n' \
        "$d" "$c1" "$w" "$t" "$wm" \
        "$c3" "$k" "$t" "$kern" \
        "$d" "$(eyes $1)" "$t" "$c2" "$s" "$t" "$shell" \
        "$c1" "$t" "$c3" "$t" "$c1" "$t" "$c5" "$r" "$t" "$res" \
        "$c4" "$n" "$t" "$net"
}

bunnyfetch() {
    printf '\n             %s%s%b  %s%s\n   (\ /)     %s%b  %s%s\n   ( %s%s%s)    %s%b  %s%s\n   c(%s"%s)(%s"%s)   %s%b  %s%s\n             %s%b  %s%s\n\n' \
        "$d" "$c1" "$w" "$t" "$wm" \
        "$c3" "$k" "$t" "$kern" \
        "$d" "$(eyes $1)" "$t" "$c2" "$s" "$t" "$shell" \
        "$c1" "$t" "$c1" "$t" "$c5" "$r" "$t" "$res" \
        "$c4" "$n" "$t" "$net"
}
```

**Comment by cybardev** [comment]
Sorry for the trouble; figured it out:
```sh
sysinfo() {
    for ch in "$d" "$c1" "$w" "$t" "$wm" \
        "$c3" "$k" "$t" "$kern" \
        "$d" "$(eyes $1)" "$t" "$c2" "$s" "$t" "$shell" \
        "$c1" "$t" "$c3" "$t" "$c1" "$t" "$c5" "$r" "$t" "$res" \
        "$c4" "$n" "$t" "$net"; do
        printf "$ch\n"
    done
}
```

---

**Edit**: that messed up the bunny for some reason, but I'll figure it out eventually. Thanks for your time.

**Edit2**: it's because the cat and the bunny have different arguments, so code was actually not duplicated (at least not completely). Sorry for the trouble.

**Comment by cybardev** [comment]
@strafe Sorry to bother you again, but could you please tell me how you found out which icon is which?

On the Nerd Font Cheat Sheet website (https://www.nerdfonts.com/cheat-sheet), I found the following:

![image](https://user-images.githubusercontent.com/50134239/150868267-e7785233-7977-46f8-85d5-c2354abf8a16.png)

But your shell icon seems to be `\xEF\x84\xA0`

I'd like to change it to the filled terminal (1st glyph in the above picture).

How would I go about converting `e795` to the format expected?

**Comment by strafe** [comment]
If you enter the code points (`e795` in this case) into this website (https://www.cogsci.ed.ac.uk/~richard/utf-8.html), you'll see the bytes you need to use under "Hex UTF-8 bytes". Then just make sure you prefix them in the same way with `\x`.

**Comment by cybardev** [comment]
Ah, wow. Thanks a lot. I'll do that.
Thanks for the help; have a nice day. 😊

**Comment by cybardev** [comment]
@strafe Sorry to bother you again, but in your script, what do the variables in lines 34-36 do? I think `$t` is a termination symbol for colours, but I don't know what `$d` and `$v` are doing.

**Comment by strafe** [comment]
> @strafe Sorry to bother you again, but in your script, what do the variables in lines 34-36 do? I think `$t` is a termination symbol for colours, but I don't know what `$d` and `$v` are doing.

No problem. All of these variable including the `c*` ones above are being set to escape codes that control how text printed after them is displayed. Most of this comes from elenpan's original script and I haven't had a reason to modify it so things are a little funky.
- `c*` are used to set the colour of text that comes after them.
- `d` is used to make the text that comes after it bold.
- `t` resets the effects of any previously used escape codes.
- `v` doesn't appear to actually get used in the script, but if it was, it would swap the text and background colours so that light text on a dark background would appear as dark text with a light background.

**Comment by cybardev** [comment]
I see. Thanks a lot. I was asking so I can include this information in the comments of my "fork" because I just copy-pasted that part without understanding any of it.

Now I understand what they do. Thanks a lot 😊
