### ISSUE TITLE
Weird Resolution on Multiple Displays

### ISSUE THREAD

**Issue by cybardev** [strafe/bunnyfetch#2]
I have two displays: an FHD monitor, and the MacBook display. The resolution appears "squashed" together like in the following image.

![image](https://user-images.githubusercontent.com/50134239/150557961-dd8a9596-8edb-4127-a675-e4d484fdb712.png)

I've tweaked the code slightly to only print the resolution of the Retina display by changing:

```sh
resolution="$(system_profiler SPDisplaysDataType | awk '/Resolution:/ {printf $2"x"$4""}')"
```

to:

```sh
resolution="$(system_profiler SPDisplaysDataType | grep Retina | awk '/Resolution:/ {printf $2"x"$4""}')"
```

Which displays the following:

![image](https://user-images.githubusercontent.com/50134239/150559816-28c26875-a9b6-41e6-bf21-21e7433203aa.png)

But ideally, I would want to display both resolutions with a comma to separate them.
The update would also ideally support more displays, so I'd prefer not to hardcode it.

Here's the output from `system_profiler SPDisplaysDataType | grep Resolution`:
```
Resolution: 1920 x 1080 (1080p FHD - Full High Definition)
Resolution: 2560 x 1600 Retina
```

I'm not very good with `awk`, `sed`, etc.
Could you please guide me on how I can achieve this?

**Comment by strafe** [comment]
Let me know if this is resolved, seems to be.

**Comment by cybardev** [comment]
> Let me know if this is resolved, seems to be.

Yep, all's well now. Thanks a lot. 😊

![image](https://user-images.githubusercontent.com/50134239/150665970-ebfa797f-0762-4efb-ac06-f82395e64825.png)
